# Site settings
name: Pragatheiswar Giri
title: Pragatheiswar Giri
description: Biomedical scientist working in Cancer research, passionate about machine learning Robotics
url: https://pragatheis.github.io/
baseurl: ''
email: pgiri@purdue.edu
resume: CV.pdf
social:
  - title: email
    url: mailto:pgiri@purdue.edu
  - title: github
    url: https://github.com/pragatheis
  - title: linkedin
    url: https://linkedin.com/in/pragatheis
  - title: Google Scholar
    url: https://scholar.google.com/citations?user=TWgrVQgAAAAJ

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
